version: '3'
services:
  db:
    image: postgres:latest
    container_name: db_postgres_dk
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      TZ: 'UTC'
    ports:
      - '${DB_PORT}:${DB_PORT_DK}'
    expose:
      - '5432'
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: api_sorelle
    command: sh -c "python3 manage.py makemigrations --noinput && python3 manage.py migrate --noinput && python3 manage.py runserver 0.0.0.0:9000"
    # command: sh -c "python3 manage.py test"
    restart: always
    env_file:
      - ./.env
    networks:
      - backend
    volumes:
      - .:/app_be
    ports:
      - "9000:9000"
    depends_on:
      - db
volumes:
  pgdata:

networks:
  backend:
     driver: bridge