version: '3'
services:
  db:
    image: postgres:latest
    container_name: db_postgres_dk
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      TZ: 'UTC'
    ports:
      - '${DB_PORT}:${DB_PORT_DK}'
    expose:
      - '5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: