# Generated by Django 3.0.8 on 2024-04-17 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('datecreate', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('delete', 'Delete'), ('suspended', 'Suspended')], default='active', max_length=10)),
                ('description', models.CharField(max_length=555)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('normal', 'Normal'), ('admin', 'Admin'), ('superadmin', 'SuperAdmin')], default='normal', max_length=10)),
                ('email', models.EmailField(max_length=500)),
                ('birthdate', models.DateField()),
                ('datecreate', models.DateField(auto_now=True)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('status', models.CharField(choices=[('active', 'Active'), ('delete', 'Delete'), ('suspended', 'Suspended')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('datecreate', models.DateField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='project.User')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesional', to='project.User')),
                ('service', models.ManyToManyField(to='project.Service', verbose_name='servicios')),
            ],
        ),
    ]
