# Generated by Django 3.0.8 on 2024-04-25 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20240425_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('datecreate', models.DateField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='project.User')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesional', to='project.User')),
                ('service', models.ManyToManyField(to='project.Service', verbose_name='servicios')),
            ],
        ),
    ]
