name: DJango Test

on: [push, pull_request]

jobs:
  test:
    name: Run Django tests
    runs-on: ubuntu-latest
    environment: 
      name: sorelle

    services:
      db_postgres_dk:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASS }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r ./django_sorelle/requirements.txt

    - name: Migrations
      run: |
        docker ps
        export DB_USER=${{ secrets.DB_USER }}
        export DB_NAME=${{ secrets.DB_NAME }}
        export DB_PASS=${{ secrets.DB_PASS }}
        export DB_PORT=${{ secrets.DB_PORT }}
        export DB_HOST=localhost
        python3 manage.py makemigrations 
        python3 manage.py migrate
        
    - name: Run tests
      run: |
        
        python manage.py test