name: DJango Test

on: [push, pull_request]

jobs:
  test:
    name: Run Django tests
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password1234
          POSTGRES_DB: sorelle
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r ./django_sorelle/requirements.txt

    - name: Migrations
      run: |
        python3 manage.py makemigrations 
        python3 manage.py migrate

    - name: Run tests
      run: |
        python manage.py test